
=head1 INSTALLATION


=head2 UNIX

- B<Unpack the archive>

- B<perl Makefile.PL>

You will be asked if you want to compile in support for Apache mod_perl. If
you say yes, the source of Apache is searched (for headerfiles). If 
it can't found, please specify the basepath. Please make sure 
mod_perl is already installed. If you have installed mod_perl-0.96 or
higher, Makefile.PL automatically suggests the same source path as was 
used to build mod_perl.

- B<make>

- B<make test>

- B<make install>

B<NOTE 1:> (only Embperl-1.2b1 or higher) For using session handling you need
Apache::Session-1.00 or higher. If possible use Apache::Session 1.52 or higher.
Starting with Embperl 1.3b7 Apache::Session 0.17 is B<NOT> supported anymore.

B<NOTE 2:> I<Embperl> runs without additional Perl modules, but the C<make test>
needs the following modules to work:

=over 4

=item * URI

=item * MIME::Base64 

=item * HTML::Parser 

=item * HTML::HeadParser 

=item * Digest::MD5 

=item * libnet 

=item * libwww 

=item * libwin32 (only Win32) 

=back

B<NOTE 3:> I<EmbperlObject> needs the following modules to work:

=over 4

=item * File::Spec 0.8 or higher

=back

If you have already successfully build and tested C<mod_perl> all modules
will already be there.

=head2 Options for make test

C<make test> can take several options, which can be given with the C<TESTARGS>
parameter:

  make test TESTARGS="--help"

will show you a list of available option. Most of them you will never need,
they are mainly nesseccary for debugging I<Embperl> itself.


=head2 Debian packages

The Debian packages are maintained by Angus Lees. Here are his
installation hints:

i've also setup an apt repository for those using stable (potato). to
use it, just add these lines to /etc/apt/sources.list (deb-src line is
only necessary if you want to download the source at some point):

  deb http://www.cse.unsw.edu.au/~gusl/embperl stable/binary-$(ARCH)/
  deb-src http://www.cse.unsw.edu.au/~gusl/embperl stable/source/

then run "apt-get update" followed by either
"apt-get install libhtml-embperl-perl" or just "apt-get upgrade" if
you already have embperl installed.

if you don't like apt, and want to do it the old fashioned way, i'm
sure you can work out how to download the .deb manually.


notes:

currently i only have i386 packages built for stable. if anyone wants
to build other archs and let me know, i can add them in (else, i can
probably get a sparc and alpha version compiled)


the package for unstable is compiled against perl5.6, so it has to
conflict with earlier mod_perl packages that are compiled against
perl5.5. unfortunately, there is no perl5.6 apache-perl package yet
(drow assures me he's uploading one soon), so you have to make do with
a DSO mod-perl (ie: apache + libapache-mod-perl) for now.


=head2 UNIX (without Apache Source)

If you have an UNIX with preinstalled Apache and mod_perl (e.g. a Linux 
distribution), you need to locate the following files on your disk:

 - httpd.h
 - httpd
 - mod_env.so

For example in SuSE Linux 7.1 they could be found at

 - /usr/include/apache/httpd.h
 - /usr/sbin/httpd
 - /usr/lib/apache/mod_env.so

Now go to the Embperl directory and start 

 perl Makefile.PL

When get asked for the Apache sources, enter the directory where you
found C<httpd.h> (e.g. C</usr/include/apache>). For the Apache executable
enter the path to C<httpd>. If the Apache modules are loaded dynamicly,
the you will get ask for C<mod_env.so>, enter it's directory. Now you can
continue as normal with

 make test
 make install
  

=head2 WIN 32 (non ActiveState Perl)


B<NOTE:> You need mod_perl >= 1.12 on win32


On Windows 95/NT you have to do the following:

B<perl Makefile.PL>

B<nmake> (you must have the c compiler in your path)

if you get an error about compiling Embperl.c. Edit Embperl.c and change

-#line  "Embperl.xs"

to

+#line  1 "Embperl.xs"

now re-run nmake and it should compile.

B<nmake test>

B<NOTE:> nmake test needs libwin32, libwww and HTML::Parser installed to work

B<nmake install>

B<NOTE 1:> (only Embperl-1.2b1 or higher) For using session handling you need
Apache::Session-1.00 or higher. If possible use Apache::Session 1.52 or higher.
Starting with Embperl 1.3b7 Apache::Session 0.17 is B<NOT> supported anymore.

B<NOTE 2:> I<Embperl> runs without additional Perl modules, but the C<make test>
needs the following modules to work:

=over 4

=item * URI

=item * MIME::Base64 

=item * HTML::Parser 

=item * HTML::HeadParser 

=item * Digest::MD5 

=item * libnet 

=item * libwww 

=item * libwin32 (only Win32) 

=back

B<NOTE 3:> I<EmbperlObject> needs the following modules to work:

=over 4

=item * File::Spec 0.8 or higher

=back

If you have already successfully build and tested C<mod_perl> all modules
will already be there.


=head2 WIN 32 with ActiveState Perl

First get and install ActiveState Perl from http://www.activestate.com

You can skip the installation of Apache and mod_perl, if you only want
to use Embperl offline or as CGI.

Next get the Apache binary (including the source e.g. apache_1.3.19-win32-src-r2.msi) from        
http://www.apache.org/dist/httpd/binaries/win32/ . (You may need to install the
windows MSI installer from the same page too). Now run the installation.

Then run the ppm program to install mod_perl

  ppm install http://theoryx5.uwinnipeg.ca/ppmpackages/mod_perl-1.25_1.3.19.ppd

If you get asked for the Apache directory, enter the C<modules> subdirectory under the path
where you have installed your Apache, e.g. 

  \Program Files\Apache Group\Apache\modules

As last step you can install the Embperl ppd:

  ppm install http://theoryx5.uwinnipeg.ca/ppmpackages/HTML-Embperl.ppd


=head2 Compile Embperl from the sources on WIN 32 with ActiveState Perl

First install ActiveState Perl, Apache and mod_perl as described above. Make sure
you have an Apache version which includes the sources. (Of course when you want to use
Embperl only offline or as CGI you don't have to install Apache and mod_perl)

Then extract the Embperl distribution and go to the directory where you have extracted
Embperl. Start

  perl Makefile.PL

Enter y or hit enter when you get ask "Build with support for Apache mod_perl?(y/n) [y]"
When get asked for the Apache source enter the Apache directory you have installed above.
e.g. \Program Files\Apache Group.

Now you can continue by running 

  nmake test
  nmake install  


=head2 How to continue

You can view the documentation at any time from the Embperl source directory,
by using the following commands metioned below. After the installation you can
also view documention by specifying the full module name: e.g.

perldoc HTML::Embperl, perldoc HTML::Embperl::Intro etc.

To get familiar how Embperl works, read the L<"Intro"|"Intro.pod"> and
L<"IntroEmbperlObject"|"IntroEmbperlObject.pod"> documents. 
To learn how to use and configure Embperl, read the L<"Embperl documentation"|"Embperl.pod">.


=head2 Further Documentation (english)


See L<"perldoc Features"|"Features.pod"> for list of Embperls features 

See L<"perldoc Intro"|"Intro.pod"> for an step by step 
introduction to Embperl.

See L<"perldoc IntroEmbperlObject"|"IntroEmbperlObject.pod"> for an step by step 
introduction to the OO features of Embperl.

See L<"perldoc Embperl"|"Embperl.pod"> for complete documentation.

See the L<"eg/"|"Examples.pod"> directory for examples.

See L<"perldoc Faq"|"Faq.pod"> for Frequently Asked Questions.

See L<"perldoc TipsAndTricks"|"TipsAndTricks.pod"> for Tips and Tricks 
around Embperl.

or you can view it online on http://perl.apache.org/embperl/

=head2 Further Documentation (german)

See B<perldoc FeaturesD> for list of Embperls features 

See B<perldoc IntroD> for an step by step 
introduction to Embperl.

See B<perldoc EmbperlD> for complete documentation.

or you can view it online on http://www.ecos.de/embperl/


